### ISSUE TITLE
Audacity crashed (sigsev) while playing an mp3 on Wayland

### ISSUE THREAD

**Issue by ericschdt** [audacity/audacity#2827]
**Describe the bug**
Audacity crashed while playing an mp3 on Wayland

```
#0  0x00007f5aaa2fdf8e in wxConvBrokenFileNames::GetMBNulLen() const (this=<optimized out>) at ./include/wx/strconv.h:230
#1  0x00007f5aaa8eb2cc in wxMBConv::FromWChar(char*, unsigned long, wchar_t const*, unsigned long) const (this=0x7f5aaa7d1f50 <wxApp::Initialize(int&, wchar_t**)::fileconv>, dst=0x0, dstLen=0, src=0x7f5aa49e6f90 L"", srcLen=0) at ./src/common/strconv.cpp:306
#2  0x00007f5aaa8f2cc8 in wxString::AsChar(wxMBConv const&) const (this=0x7f5aa49e6f80, conv=...) at ./src/common/string.cpp:532
#3  0x00007f5aaa8acacb in wxString::AsCharBuf(wxMBConv const&) const (conv=<optimized out>, this=0x7f5aa49e6f80) at ./include/wx/string.h:3656
#4  wxString::mb_str(wxMBConv const&) const (conv=<optimized out>, this=0x7f5aa49e6f80, this=<optimized out>, conv=<optimized out>) at ./include/wx/string.h:1836
#5  wxString::fn_str() const (this=0x7f5aa49e6f80) at ./include/wx/string.h:1853
#6  wxStat(wxString const&, stat*) (buf=0x7f5aa49e6fb0, path=...) at ./include/wx/filefn.h:418
#7  (anonymous namespace)::DoStatAny(stat&, wxString, bool) (st=..., path=..., dereference=<optimized out>) at ./src/common/filename.cpp:332
#8  0x00007f5aaa8b6038 in (anonymous namespace)::StatAny (flags=2, path=..., st=...) at ./src/common/filename.cpp:341
#9  (anonymous namespace)::wxFileSystemObjectExists(wxString const&, int) (path=<optimized out>, flags=2) at ./src/common/filename.cpp:670
#10 0x00007f5aaa8baae3 in (anonymous namespace)::CheckIfDirExists (dir=...) at ./src/common/filename.cpp:1201
#11 wxFileName::GetTempDir() () at ./src/common/filename.cpp:1211
#12 0x00007f5aa9ed7d03 in wxDebugReport::wxDebugReport() (this=this@entry=0x7f5aa49e7650, this=<optimized out>) at ./src/common/debugrpt.cpp:197
#13 0x0000558882650dbf in wxDebugReportCompress::wxDebugReportCompress() (this=0x7f5aa49e7650) at /usr/include/wx-3.1/wx/debugrpt.h:140
#14 CrashReport::Generate(wxDebugReport::Context) (ctx=<optimized out>) at /usr/src/debug/audacity-3.0.5-4.2.x86_64/src/CrashReport.cpp:37
#15 0x00005588825f4d00 in AudacityApp::OnFatalException() (this=<optimized out>) at /usr/src/debug/audacity-3.0.5-4.2.x86_64/src/AudacityApp.cpp:961
#16 0x00007f5aaa95cae2 in wxFatalSignalHandler(int) () at ./src/unix/utilsunx.cpp:1418
#17 0x00007f5aa89d63d0 in <signal handler called> () at /lib64/libc.so.6
#18 0x00007f5aaa857bca in wxThreadSpecificInfo::ThreadCleanUp() () at ./src/common/threadinfo.cpp:74
#19 0x00007f5aaa953be4 in wxScopeGuardImpl0<void (*)()>::Execute() (this=0x7f5aa49e88a0) at ./include/wx/scopeguard.h:35
#20 wxPrivate::OnScopeExit<wxScopeGuardImpl0<void (*)()> >(wxScopeGuardImpl0<void (*)()>&) (guard=...) at ./include/wx/scopeguard.h:42
#21 wxScopeGuardImpl0<void (*)()>::~wxScopeGuardImpl0() (this=0x7f5aa49e88a0, this=<optimized out>) at ./include/wx/scopeguard.h:108
#22 wxThread::CallEntry() (this=0x5588851df1a0) at ./include/wx/thrimpl.cpp:357
#23 0x00007f5aaa958b31 in wxThreadInternal::PthreadStart(wxThread*) (thread=0x5588851df1a0) at ./src/unix/threadpsx.cpp:891
#24 0x00007f5aa8a242ba in start_thread (arg=<optimized out>) at pthread_create.c:442
#25 0x00007f5aa8aae460 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

```
(gdb) list
225         }
226
227         virtual size_t GetMBNulLen() const wxOVERRIDE
228         {
229             // cast needed to call a private function
230             return m_conv->GetMBNulLen();
231         }
232
233         virtual bool IsUTF8() const wxOVERRIDE { return m_conv->IsUTF8(); }
234
```

**Additional information (please complete the following information):**
 - OS: openSUSE TW
 - Version Audacity 3.0.5

**Comment by LWinterberg** [comment]
Can you try with the current version (3.1.3)?

**Comment by ericschdt** [comment]
> Can you try with the current version (3.1.3)?

It has updated on openSUSE TW to 3.1.3 now, but I cannot start it any longer, there seems to be a packaging problem:
```
/usr/bin/audacity: error while loading shared libraries: lib-screen-geometry.so: cannot open shared object file: No such file or directory
```
but it should come with audacity itself
```
> zypper se --provides lib-screen-geometry.so
S  | Name     | Summary                            | Type
---+----------+------------------------------------+------
i+ | audacity | A Multi Track Digital Audio Editor | Package
```
as far as I can see it.
