### ISSUE TITLE
Strange "virtual environment" error

### ISSUE THREAD

**Issue by gvanem** [audacity/audacity#4270]
### Bug description

Trying to build using simply `md build & cmake -G "NMake Makefiles"  ..`, I get this output:
```
-- The C compiler identification is MSVC 19.35.32124.0
-- The CXX compiler identification is MSVC 19.35.32124.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: F:/gv/VC_2022/VC/Tools/MSVC/14.35.32124/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: F:/gv/VC_2022/VC/Tools/MSVC/14.35.32124/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: F:/gv/Python310/python3.exe (found version "3.10.5") found components: Interpreter
-- The ASM_NASM compiler identification is NASM
-- Found assembler: F:/util/nasm.exe
-- Build Info:
--   Host System: Windows-10.0.19045
--   Host System Name: Windows
--   Host System Processor: AMD64
--   Host System Version: 10.0.19045
--   Host System Architecture: 64-bit
....

  File "F:\gv\Python310\lib\ntpath.py", line 718, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'c:', start on mount 'F:'
WARNING: You are using pip version 22.0.4; however, version 23.0 is available.
You should consider upgrading via the 'F:\MinGW32\src\Sound\Audacity\src\gv-build\conan_venv\Scripts\python.exe -m pip install --upgrade pip' command.
Creating Conan virtual environment F:\MinGW32\src\Sound\Audacity\src\gv-build\conan_venv
Traceback (most recent call last):
  File "F:\MinGW32\src\Sound\Audacity\src\conan\conan_runner.py", line 322, in <module>
    conan_version = validate_conan(args.build_dir)
  File "F:\MinGW32\src\Sound\Audacity\src\conan\conan_runner.py", line 131, in validate_conan
    build_venv(conan_venv)
  File "F:\MinGW32\src\Sound\Audacity\src\conan\conan_runner.py", line 97, in build_venv
    builder.create(conan_venv)
  File "F:\gv\Python310\lib\venv\__init__.py", line 78, in create
    self.post_setup(context)
  File "F:\MinGW32\src\Sound\Audacity\src\conan\conan_runner.py", line 21, in post_setup
    subprocess.check_call(cmd)
  File "F:\gv\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['F:\\MinGW32\\src\\Sound\\Audacity\\src\\gv-build\\conan_venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'conan']' returned non-zero exit status 2.
CMake Error at cmake-proxies/cmake-modules/AudacityDependencies.cmake:197 (message):
  Conan failed to install dependencies (1) F:/gv/Python310/python3.exe
Call Stack (most recent call first):
  CMakeLists.txt:567 (include)

-- Configuring incomplete, errors occurred!
```

The error **`path is on mount 'c:', start on mount 'F:'`** is totally meaningless to me.
What's on `C:` and what's on `F:` that pip is complaining about?

### Steps to reproduce

I got the same error using `CMake-gui.exe`.

### Expected behavior

A successful configure with working NMake Makefiles.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by crsib** [comment]
Well, it appears that Conan doesn't handle the case where `CONAN_USER_HOME` and `CONAN_USER_HOME_SHORT` are on different drives.
