### ISSUE TITLE
ALSA lib pcm.c:8503:(snd_pcm_recover) underrun occurred

### ISSUE THREAD

**Issue by chrissound** [audacity/audacity#512]
**Describe the bug**

Audacity crashes / hangs sporadically. I've just tried to replicate it again, and although it doesn't crash, it doesn't play back the audio correctly (just weird glitchy sounds). The output has the following:
```
ALSA lib pcm.c:8503:(snd_pcm_recover) underrun occurred
```

```
audacity --version

(audacity:5266): Gtk-WARNING **: 17:29:57.633: Unable to locate theme engine in module_path: "adwaita",
Audacity v2.3.2
```

**Comment by j39m** [comment]
Piggybacking off your existing bug report to describe a fairly consistently reproducible crash on my system with similar symptoms. Observed on Fedora 32 x86_64 using this version:

```
[j39m@flaglock6 ~/Downloads/tmp]
$ audacity --version
Audacity v2.3.3
[j39m@flaglock6 ~/Downloads/tmp]
$ rpm -q audacity-freeworld
audacity-freeworld-2.3.3-3.fc32.x86_64
```

To reproduce, I run Audacity, let settle, and attempt to record audio.
```
[snip]
02:25:50: Debug: Unrecognized accel key 'numpad_enter', accel string ignored.
02:25:50: Debug: Unrecognized accel key 'numpad_enter', accel string ignored.
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
Expression 'err' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3355
Expression 'ContinuePoll( self, StreamDirection_In, &pollTimeout, &pollCapture )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3881
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4253
audacity: src/hostapi/alsa/pa_linux_alsa.c:3387: OnExit: Assertion `data' failed.
Aborted (core dumped)
```

The trace is as follows:

```
(gdb) bt full
#0  0x00007fda082e69e5 in raise () at /lib64/libc.so.6
#1  0x00007fda082cf895 in abort () at /lib64/libc.so.6
#2  0x00007fda082cf769 in _nl_load_domain.cold () at /lib64/libc.so.6
#3  0x00007fda082dee76 in annobin_assert.c_end () at /lib64/libc.so.6
#4  0x00005575cf163544 in OnExit (data=0x0) at src/hostapi/alsa/pa_linux_alsa.c:3387
        __PRETTY_FUNCTION__ = "OnExit"
        stream = <optimized out>
        __PRETTY_FUNCTION__ = "OnExit"
#5  OnExit (data=<optimized out>) at src/hostapi/alsa/pa_linux_alsa.c:3383
        stream = <optimized out>
        __PRETTY_FUNCTION__ = "OnExit"
#6  0x00005575cf1684f1 in __pthread_cleanup_routine (__frame=<synthetic pointer>)
    at /usr/include/pthread.h:587
        __clframe =
          {__cancel_routine = 0x5575cf1634e0 <OnExit>, __cancel_arg = 0x0, __do_it = 1, __cancel_type = <optimized out>}
        result = -9999
        stream = 0x5575cffe5a60
        timeInfo = {inputBufferAdcTime = 0, currentTime = 0, outputBufferDacTime = 0}
        callbackResult = 0
        cbFlags = 0
        streamStarted = <optimized out>
        __PRETTY_FUNCTION__ = "CallbackThreadFunc"
#7  CallbackThreadFunc (userData=0x5575cffe5a60) at src/hostapi/alsa/pa_linux_alsa.c:4185
        __clframe =
          {__cancel_routine = 0x5575cf1634e0 <OnExit>, __cancel_arg = 0x0, __do_it = 1, __cancel_type = <optimized out>}
        result = -9999
        stream = 0x5575cffe5a60
        timeInfo = {inputBufferAdcTime = 0, currentTime = 0, outputBufferDacTime = 0}
        callbackResult = 0
        cbFlags = 0
        streamStarted = <optimized out>
        __PRETTY_FUNCTION__ = "CallbackThreadFunc"
#8  0x00007fda0baa8432 in start_thread () at /lib64/libpthread.so.0
#9  0x00007fda083ab913 in clone () at /lib64/libc.so.6
```

**Comment by SteveDaulton** [comment]
Audacity 2.3.2 is no longer being developed. Is this issue reproducible with Audacity 2.4.2 ?

**Comment by j39m** [comment]
My issue is partially reproducible in Audacity 2.4.2 via the Fedora 32 Flatpak, but it hangs rather than crashing:

Same reproduction steps:

```
[snip]
ALSA lib ../../../src/pcm/pcm.c:8432:(snd_pcm_recover) underrun occurred
Expression 'err' failed in '../lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 3355
Expression 'ContinuePoll( self, StreamDirection_In, &pollTimeout, &pollCapture )' failed in '../lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 3896
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in '../lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 4274
sh: addr2line: command not found
^C
```

**Comment by ingobecker** [comment]
I'm having the same issue. I'm using audacity 2.3.3 on fedora 31 and if i hit the space bar multiple times quickly in a row to start and stop the playback, audacity first has problems with playback, mixing in random noise but if i keep hitting space, audacity will just freeze. Audacity from flathub in version 2.4.2 using fedora 31 hardly plays any audio. Its just glitchy noise 9 out of 10 times i hit the play button. At least, in this version the application doesn't freeze, hitting the space bar quickly consecutively.

**Comment by noarchwastaken** [comment]
> Audacity 2.3.2 is no longer being developed. Is this issue reproducible with Audacity 2.4.2 ?

Reproducible on Fedora 33, both RPM and Flathub builds.

```
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
```

note that the audio plays tens of times faster than it should be.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
