### ISSUE TITLE
Compile error on Arch linux with git master sources from 2024-05-01

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#6370]
### Bug description

As of 1st of May 2024, the git master branch does not build on Linux. 

### Steps to reproduce

On Arch Linux, run the command: yay -S audacity-local-git

### Expected behavior

A clean build and install

### Actual behavior

The build fails with the following error in the terminal:
```
- ========== Using Conan version of PortMidi ==========
-- ========== Using system version of vst3sdk ==========
-- Found libuuid: 
        libuuid_INCLUDE_DIR: /usr/include
        libuuid_LIBRARIES: /usr/lib/libuuid.so
'/usr/bin/python3.12' '/mnt/int/system/aur/audacity-local-git/src/audacity/conan/conan_runner.py' '--build-dir' '/mnt/int/system/aur/audacity-local-git/src/build' '--compiler' 'GNU' '--compiler-version' '13.2.1' '--build-types' 'Release' '--target-arch' 'x86_64' '--build-arch' 'x86_64' '--lib-dir' 'lib/audacity' '-o' 'use_wxwidgets=True' 'use_jack=True' 'use_portmidi=True'
Traceback (most recent call last):
  File "/usr/bin/conan", line 33, in <module>
    sys.exit(load_entry_point('conan==2.2.2', 'console_scripts', 'conan')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/conan", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/conans/conan.py", line 3, in <module>
    from conan.cli.cli import main
  File "/usr/lib/python3.12/site-packages/conan/__init__.py", line 2, in <module>
    from conan.tools.scm import Version as _Version
  File "/usr/lib/python3.12/site-packages/conan/tools/scm/__init__.py", line 1, in <module>
    from conan.tools.scm.git import Git
  File "/usr/lib/python3.12/site-packages/conan/tools/scm/git.py", line 5, in <module>
    from conan.tools.files import chdir, update_conandata
  File "/usr/lib/python3.12/site-packages/conan/tools/files/__init__.py", line 5, in <module>
    from conan.tools.files.patches import patch, apply_conandata_patches, export_conandata_patches
  File "/usr/lib/python3.12/site-packages/conan/tools/files/patches.py", line 5, in <module>
    import patch_ng
ModuleNotFoundError: No module named 'patch_ng'
Traceback (most recent call last):
  File "/mnt/int/system/aur/audacity-local-git/src/audacity/conan/conan_runner.py", line 91, in <module>
    conan_version = validate_conan(required_conan_version)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/int/system/aur/audacity-local-git/src/audacity/conan/helpers/conan_environment.py", line 141, in validate_conan
    conan_version = get_conan_version()
                    ^^^^^^^^^^^^^^^^^^^
  File "/mnt/int/system/aur/audacity-local-git/src/audacity/conan/helpers/conan_environment.py", line 90, in get_conan_version
    version_string = subprocess.check_output([get_conan(), '--version'], stdin=subprocess.DEVNULL).decode('utf-8').strip()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['conan', '--version']' returned non-zero exit status 1.
CMake Error at cmake-proxies/cmake-modules/AudacityDependencies.cmake:209 (message):
  Conan failed to install dependencies (1) /usr/bin/python3.12
Call Stack (most recent call first):
  CMakeLists.txt:586 (include)


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: audacity-local-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
audacity-local-git - exit status 4
[evert@Evert ~]$ python --version
Python 3.12.3
[evert@Evert ~]$
```

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Details on my system:
```
Operating System: Arch Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.8-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: TUXEDO
Product Name: PD5x_7xSNC_SND_SNE
```

**Comment by evertvorster** [comment]
Oh, and python patch-ng is installed:
```
[evert@Evert ~]$ yay -Ss patch-ng
aur/python-patch-ng 1.17.4-3 (+11 0.00) (Installed)
    Library to parse and apply unified diffs forked from python-patch.
[evert@Evert ~]$ yay -Ql python-patch-ng
python-patch-ng /usr/
python-patch-ng /usr/lib/
python-patch-ng /usr/lib/python3.11/
python-patch-ng /usr/lib/python3.11/site-packages/
python-patch-ng /usr/lib/python3.11/site-packages/__pycache__/
python-patch-ng /usr/lib/python3.11/site-packages/__pycache__/patch_ng.cpython-311.opt-1.pyc
python-patch-ng /usr/lib/python3.11/site-packages/__pycache__/patch_ng.cpython-311.pyc
python-patch-ng /usr/lib/python3.11/site-packages/patch_ng-1.17.4-py3.11.egg-info/
python-patch-ng /usr/lib/python3.11/site-packages/patch_ng-1.17.4-py3.11.egg-info/PKG-INFO
python-patch-ng /usr/lib/python3.11/site-packages/patch_ng-1.17.4-py3.11.egg-info/SOURCES.txt
python-patch-ng /usr/lib/python3.11/site-packages/patch_ng-1.17.4-py3.11.egg-info/dependency_links.txt
python-patch-ng /usr/lib/python3.11/site-packages/patch_ng-1.17.4-py3.11.egg-info/top_level.txt
python-patch-ng /usr/lib/python3.11/site-packages/patch_ng.py
[evert@Evert ~]$ 
```

**Comment by evertvorster** [comment]
It now builds.... Strange. Must have been a transient issue with my system.
