### ISSUE TITLE
Crash when recording

### ISSUE THREAD

**Issue by grliszas14** [audacity/audacity#6678]
Latest Audacity (built from master) crashes after a while of recording.

Steps to reproduce:
1. Open Audacity
2. Hit record button
3. Wait few seconds

Happens on my Linux Ubuntu 22.04 and Martin's macOS

I was able to track down commit that introduces it: https://github.com/audacity/audacity/pull/6391
Looks like cache is cleared too soon, then app tries to access it and we get segfault

Stacktrace:

> Thread 1 "audacity" received signal SIGSEGV, Segmentation fault.
> 0x00007ffff78a2f95 in ColorFunction::GetColor (this=0x10, row=79, defaultColor=...) at /home/grliszas14/Projects/audacity-fork/libraries/lib-wave-track-paint/waveform/WaveBitmapCache.cpp:66
> 66	      for (auto stop : Stops)
> (gdb) bt full
> #0  0x00007ffff78a2f95 in ColorFunction::GetColor(unsigned int, Triplet) const (this=0x10, row=79, defaultColor=...)
>     at /home/grliszas14/Projects/audacity-fork/libraries/lib-wave-track-paint/waveform/WaveBitmapCache.cpp:66
>         stop = {first = {r = 240 '\360', g = 243 '\363', b = 255 '\377', unused = 0 '\000'}, second = 136}
>         __for_range = <error reading variable: Cannot access memory at address 0x10>
>         __for_begin = 0x10
>         __for_end = 0x48
> #1  0x00007ffff78a284e in WaveBitmapCache::InitializeElement(GraphicsDataCacheKey const&, WaveBitmapCacheElement&)
>     (this=0x55555786cc70, key=..., element=...)
>     at /home/grliszas14/Projects/audacity-fork/libraries/lib-wave-track-paint/waveform/WaveBitmapCache.cpp:398
>         color = {r = 240 '\360', g = 243 '\363', b = 255 '\377', unused = 0 '\000'}
>         pixel = 0
>         colorFunction = 0x10
>         row = 79
>         sw = {mSection = FrameStatistics::SectionID::WaveBitmapCache, mStart = {__d = {__r = 1718274385178308183}}}
>         columnsCount = 256
>         defaultColor = {r = 69 'E', g = 72 'H', b = 90 'Z', unused = 0 '\000'}
>         height = 136
>         rowData = 0x555558937090 "\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360\363\377\360", <incomplete sequence \363>...
> #2  0x00007ffff78a6649 in GraphicsDataCache<WaveBitmapCacheElement>::CreateElement(GraphicsDataCacheKey const&)
>     (this=0x55555786cc70, key=...) at /home/grliszas14/Projects/audacity-fork/libraries/lib-wave-track-paint/GraphicsDataCache.h:326
>         element = 0x555557ebd840

**Comment by petersampsonaudacity** [comment]
Does not appear to affect the latest alpha master (with new Themes) running on Windows

**Comment by chinakov** [comment]
Managed to reproduce the issue on the Master build, this issue is no longer reproducible within the scope of this task. Please merge it, and thank you!
