### ISSUE TITLE
[3.7.0] fails to build without soundtouch support (-Daudacity_use_soundtouch:STRING=off)

### ISSUE THREAD

**Issue by tgurr** [audacity/audacity#7814]
### Bug description

3.7.0 fails to build with `-Daudacity_use_soundtouch:STRING=off`

```
[...]
-- ========== soundtouch disabled ==========
[...]
/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-builtin-effects/ChangeTempoBase.cpp:21:10: fatal error: SoundTouch.h: No such file or directory
   21 | #include "SoundTouch.h"
      |          ^~~~~~~~~~~~~~
[...]
```

### Steps to reproduce

1. Pass CMake `-Daudacity_use_soundtouch:STRING=off`
2. See the build fail

### Expected behavior

See the build succeed (like it did with 3.5.0)

### Actual behavior

```
[...]
-- ========== soundtouch disabled ==========
[...]
[ 51%] Building CXX object libraries/lib-builtin-effects/CMakeFiles/lib-builtin-effects.dir/ChangeTempoBase.cpp.o
cd /var/tmp/paludis/build/media-sound-audacity-3.7.0/work/build/libraries/lib-builtin-effects && /usr/bin/x86_64-pc-linux-gnu-c++ -DAUDIO_DEVICES_API="" -DAUDIO_GRAPH_API="" -DAUDIO_IO_API="" -DBASIC_UI_API="" -DBUILTIN_EFFECTS_API="" -DCHANNEL_API="" -DCOMMAND_PARAMETERS_API="" -DCOMPONENTS_API="" -DDYNAMIC_RANGE_PROCESSOR_API="" -DEFFECTS_API="" -DEXCEPTIONS_API="" -DFFT_API="" -DFILES_API="" -DIPC_API="" -DLABEL_TRACK_API="" -DMATH_API="" -DMIXER_API="" -DMODULE_MANAGER_API="" -DNOTE_TRACK_API="" -DNUMERIC_FORMATS_API="" -DPLAYABLE_TRACK_API="" -DPREFERENCES_API="" -DPROJECT_API="" -DPROJECT_HISTORY_API="" -DPROJECT_RATE_API="" -DREALTIME_EFFECTS_API="" -DREGISTRIES_API="" -DSAMPLE_TRACK_API="" -DSCREEN_GEOMETRY_API="" -DSNAPPING_API="" -DSTRETCHING_SEQUENCE_API="" -DSTRINGS_API="" -DSTRING_UTILS_API="" -DTIME_AND_PITCH_API="" -DTIME_FREQUENCY_SELECTION_API="" -DTRACK_API="" -DTRACK_SELECTION_API="" -DTRANSACTIONS_API="" -DUSE_PORTMIXER=1 -DUTILITY_API="" -DWAVE_TRACK_API="" -DWAVE_TRACK_FFT_API="" -DWXUSINGDLL -DXML_API="" -D_FILE_OFFSET_BITS=64 -D_WX_APP_H_BASE_ -D_WX_BRUSH_H_BASE_ -D_WX_COLOUR_H_BASE_ -D_WX_EVTLOOP_H_ -D_WX_IMAGE_H -D_WX_PEN_H_BASE_ -D__WXGTK__ -Dlib_builtin_effects_EXPORTS -DwxUSE_GUI=0 -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-builtin-effects -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-dynamic-range-processor -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-utility -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-strings -I/usr/x86_64-pc-linux-gnu/lib/wx/include/gtk3-unicode-3.2 -I/usr/x86_64-pc-linux-gnu/include/wx-3.2 -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-wave-track-fft -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-wave-track -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-project-rate -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-project -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-registries -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-preferences -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-basic-ui -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-components -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-exceptions -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-xml -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-files -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-string-utils -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-audio-devices -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/lib-src/portmixer/include -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-math -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-sample-track -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-mixer -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-audio-graph -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-playable-track -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-track -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-channel -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-project-history -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-transactions -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-stretching-sequence -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-time-and-pitch -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/lib-src/pffft -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-track-selection -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-time-frequency-selection -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-snapping -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-numeric-formats -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-screen-geometry -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-fft -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-label-track -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-effects -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-command-parameters -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-realtime-effects -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-module-manager -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-ipc -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-note-track -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-audio-io -I/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/lib-src/portsmf -march=native -O2 -pipe -O3 -DNDEBUG -std=gnu++17 -fPIC -fdiagnostics-color=always -include /var/tmp/paludis/build/media-sound-audacity-3.7.0/work/build/src/private/configunix.h -DAUDACITY_VERSION=3 -DAUDACITY_RELEASE=7 -DAUDACITY_REVISION=0 -DAUDACITY_MODLEVEL=0 -DAUDACITY_VERSION_STRING=L\"3.7.0\" -DAUDACITY_FILE_VERSION=L\"3,7,0,0\" -Dsafenew=new -DWXINTL_NO_GETTEXT_MACRO -U_DEBUG -DIS_RELEASE -MD -MT libraries/lib-builtin-effects/CMakeFiles/lib-builtin-effects.dir/ChangeTempoBase.cpp.o -MF CMakeFiles/lib-builtin-effects.dir/ChangeTempoBase.cpp.o.d -o CMakeFiles/lib-builtin-effects.dir/ChangeTempoBase.cpp.o -c /var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-builtin-effects/ChangeTempoBase.cpp

Error:
  * In program cave perform install --hooks --managed-output --output-exclusivity with-others =media-sound/audacity-3.7.0:0::media-unofficial --destination installed --replacing =media-sound/audacity-3.5.0:0::installed --x-of-y 1 of 1:
  * When installing 'media-sound/audacity-3.7.0:0::media-unofficial' replacing { 'media-sound/audacity-3.5.0:0::installed' }:
  * When running an ebuild command on 'media-sound/audacity-3.7.0:0::media-unofficial':
  * Install failed for 'media-sound/audacity-3.7.0:0::media-unofficial' (paludis::ActionFailedError)

make[2]: Leaving directory '/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/build'

/var/tmp/paludis/build/media-sound-audacity-3.7.0/work/audacity-sources-3.7.0/libraries/lib-builtin-effects/ChangeTempoBase.cpp:21:10: fatal error: SoundTouch.h: No such file or directory
   21 | #include "SoundTouch.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

### Audacity Version

Audacity 3.7.x

### Operating system

Linux

### Additional context

Complete build log: [audacity-3.7.0_build.log](https://github.com/user-attachments/files/17956596/audacity-3.7.0_build.log)

**Comment by phileimer** [comment]
Bug still present in 3.7.3.
Just to share that I can compile after applying the patch below.

```
--- audacity-sources-3.7.3/libraries/lib-builtin-effects/CMakeLists.txt~	2025-03-13 12:54:39.000000000 +0100
+++ audacity-sources-3.7.3/libraries/lib-builtin-effects/CMakeLists.txt	2025-03-13 16:21:33.834360811 +0100
@@ -13,8 +13,6 @@
    ChangePitchBase.h
    ChangeSpeedBase.cpp
    ChangeSpeedBase.h
-   ChangeTempoBase.cpp
-   ChangeTempoBase.h
    ClickRemovalBase.cpp
    ClickRemovalBase.h
    CompressorInstance.cpp

```

**Comment by kryksyh** [comment]
@tgurr @phileimer, can you shed some light on why one would want to compile Audacity without SoundTouch? Is it simply a dependency issue?

**Comment by tgurr** [comment]
@kryksyh source-based distributions like Gentoo and Exherbo allow the user to decide what optional dependencies and features they want to build with so as long as an upstream projects offers such an option to enable/disable stuff like there is with `-Daudacity_use_soundtouch` it should work as intended.

**Comment by kryksyh** [comment]
I see, so if there are no practical reasons for keeping this option, then the most obvious fix would be to remove it. 
@tgurr, do you think it is reasonable?

**Comment by phileimer** [comment]
I use a custom distribution, based on LFS/BLFS, and don't have SoundTouch installed, and don't need it for Audacity or other package.
That's why I use the option to disable it at build time.
I tend to minimize the stuff I have to install.

**Comment by kryksyh** [comment]
@phileimer SoundTouch comes with Audacity as a source (see `lib-src/soundtouch`), so you don't have to install anything extra.

**Comment by phileimer** [comment]
@kryksyh I have a fail at configure time if  SoundTouch is enabled.
Below is a copy of the output I get.
To avoid going deeper into the problem, I just disabled SoundTouch.

```
-- Found libuuid: 
	libuuid_INCLUDE_DIR: /usr/include
	libuuid_LIBRARIES: /usr/lib/libuuid.so
'/usr/bin/python3.12' '/home/phil/src/audacity-sources-3.7.5/conan/conan_runner.py' '--build-dir' '/home/phil/src/audacity-sources-3.7.5/BUILD' '--compiler' 'GNU' '--compiler-version' '15.2.0' '--build-types' 'Release' '--target-arch' 'x86_64' '--build-arch' 'x86_64' '--lib-dir' 'lib64/audacity' '-o' 'use_portaudio=True' 'use_rapidjson=True' 'use_portmidi=True'
Using Conan version 2.7.0 (conan)
ERROR: Invalid setting '15' is not a valid 'settings.compiler.version' value.
Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '6.5', '7', '7.1', '7.2', '7.3', '7.4', '7.5', '8', '8.1', '8.2', '8.3', '8.4', '8.5', '9', '9.1', '9.2', '9.3', '9.4', '9.5', '10', '10.1', '10.2', '10.3', '10.4', '10.5', '11', '11.1', '11.2', '11.3', '11.4', '12', '12.1', '12.2', '12.3', '12.4', '13', '13.1', '13.2', '13.3', '14', '14.1', '14.2']
Read "http://docs.conan.io/2/knowledge/faq.html#error-invalid-setting"
Generating build profile...
Generating base host profile...
Generating options profile...
Generating host-debug profile...
Generating host-release profile...
Generating host-relwithdebinfo profile...
Generating host-minsizerel profile...
Traceback (most recent call last):
  File "/home/phil/src/audacity-sources-3.7.5/conan/conan_runner.py", line 109, in <module>
    subprocess.check_call(conan_options, stdin=subprocess.DEVNULL)
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conan', 'install', '/usr/src/audacity-sources-3.7.5/conan', '--build=missing', '--output-folder', '/home/phil/src/audacity-sources-3.7.5/BUILD', '--remote', 'audacity-binaries-conan2', '--profile:build', '/usr/src/audacity-sources-3.7.5/BUILD/conan/profiles/build.profile', '--profile:host', '/usr/src/audacity-sources-3.7.5/BUILD/conan/profiles/host-debug.profile']' returned non-zero exit status 1.
CMake Error at cmake-proxies/cmake-modules/AudacityDependencies.cmake:209 (message):
  Conan failed to install dependencies (1) /usr/bin/python3.12
Call Stack (most recent call first):
  CMakeLists.txt:599 (include)
```

**Comment by phileimer** [comment]
Here is my cmake configuration:

`cmake -B BUILD -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -Daudacity_lib_preference=system -Daudacity_obey_system_dependencies=on -Daudacity_use_midi=local -Daudacity_use_portsmf=local -Daudacity_use_sbsms=off -Daudacity_use_libmpg123=off -Daudacity_has_tests=off -Daudacity_use_wavpack=off -Daudacity_use_portaudio=local -Daudacity_has_vst3=off -Daudacity_use_vamp=off -D audacity_use_lv2=local -Daudacity_use_twolame=local -Daudacity_use_soxr=local -Daudacity_use_rapidjson=local -Daudacity_use_opusfile=off -Wno-dev`

**Comment by kryksyh** [comment]
@phileimer is it related to soundtouch though. Conan tells you that gcc 15 is not supported. You have conan 2.7, and gcc 15 support was added around 2.17.

**Comment by phileimer** [comment]
Likely not, but I did'nt analyze the issue.
It did'nt work either with gcc 14.

**Comment by tgurr** [comment]
> I see, so if there are no practical reasons for keeping this option, then the most obvious fix would be to remove it. [@tgurr](https://github.com/tgurr), do you think it is reasonable?

> @phileimer SoundTouch comes with Audacity as a source (see lib-src/soundtouch), so you don't have to install anything extra.

Generally distributions (https://fedoraproject.org/wiki/Bundled_Libraries) also tend to not use bundled stuff (and even have policies in this regard) wherever possible and use `-Daudacity_use_soundtouch:STRING=system`  for enabling soundtouch support. Since the build failed otherwise we had no other option to hard-enable this on our distribution already but a proper fix would of course be desireable since the statement in regards to `no practical reasons` could basically be true for all other optional dependencies and options as well.

**Comment by phileimer** [comment]
Got it. I'll try to have it built correctly. Thank you.
